### ISSUE TITLE
Invalid advertisement error

### ISSUE THREAD

**Issue by weex** [jgarzik/playground21#2]
I attempted to post an ad and get this error no matter what I put in for pubkey. I've tried a couple of addresses. Does it literally need a pubkey?

```
twenty@bitcoin-computer-i7ju:~/code/playground21/apibb$ python3 apibb-client.py post.ad causeway http://10.158.49.204:5001/help apubkey 1
Traceback (most recent call last):
  File "apibb-client.py", line 64, in <module>
    cmd_advertise(sys.argv[2], sys.argv[3], sys.argv[4], sys.argv[5])
  File "apibb-client.py", line 50, in cmd_advertise
    answer = requests.get(url=sel_url.format(name, uri, pubkey, hours))
  File "/usr/lib/python3/dist-packages/two1/lib/bitrequests/bitrequests.py", line 139, in get
    return self.request('get', url, max_price, **kwargs)
  File "/usr/lib/python3/dist-packages/two1/lib/bitrequests/bitrequests.py", line 110, in request
    payment_headers = self.make_402_payment(response, max_price)
  File "/usr/lib/python3/dist-packages/two1/lib/bitrequests/bitrequests.py", line 186, in make_402_payment
price = int(price)
ValueError: invalid literal for int() with base 10: 'invalid advertisement'
```

**Comment by jgarzik** [comment]
@weex A valid pubkey is not needed, but it does need to be at least 32 bytes in length: https://github.com/jgarzik/playground21/blob/master/apibb/apibb-server.py#L101

**Comment by weex** [comment]
I did try it with an address of 34 characters but got the same error. Couldn't tell why validate_advertisement would fail on it from looking at the code.

**Comment by weex** [comment]
I think I found it. https://github.com/jgarzik/playground21/blob/master/apibb/apibb-server.py#L111
%s doesn't get filled in with anything. Will try to fix tonight because I'd like more places to advertise stuff.

**Comment by jgarzik** [comment]
@weex Odd.  That looks correct to me...   strftime() takes expires as the argument, with %s as the conversion.

**Comment by weex** [comment]
If a record isn't in the names table, 'expires' always comes back as None, causing the validate to fail and disallowing any new ads. I was able to add a name on my server by commenting out that block. If I get some more time tonight, I'll redo that check which is simply put as "don't let someone register a name that is still active."
